version: "3"

services:

  rdfservices:
    build: .
    depends_on: 
      - graphdb
    networks:
      - net
      
  graphdb:
    build:
      context: graphdb-free/
    networks:
      - net

networks:
  net:
    driver: bridge
