version: "3"

services:

  webservice:
    build: .
    depends_on: 
      - graphdb
    ports:
      - 80:8080
    networks:
      - net
      
  graphdb:
    build:
      context: graphdb-free/
    ports:
      - 7200:7200
    networks:
      - net

networks:
  net:
    driver: bridge
