version: "3"

services:

  webservice:
    build: .
    depends_on: 
      - graphdb
    environment:
      - ENDPOINT=http://graphdb:7200/repositories/scigraph
    ports:
      - 80:8080
    networks:
      - net
      
  graphdb:
    build:
      context: graphdb-free/
      args:
        - edition=free
        - version=9.1.1
    ports:
      - 7200:7200
    #volumes:
    #  - ./data/graphdb:/opt/graphdb/home
    #  - ./data/covidgraph/scigraph/:/root/graphdb-import/
    networks:
      - net

networks:
  net:
    driver: bridge

