default:
  endpoint: http://localhost:7200/repositories/<repository_id>

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha 
    tags-sorter: alpha
  packages-to-scan: org.amalic.rdfservices.service

logging:
  level:
    root: ERROR
    org.amalic: DEBUG

server:
  port: 8080